# INFORMACIÓN DEL PROYECTO

### Título

# ¡Los jóvenes no leen!

### Tema

Los índices de lectura.

El objetivo es: Demostrar de qué depende que se lea más o menos.

Desmontamos creencias como la de que los jovenes leen menos que los adultos o la de que las pantallas son las responsables de que se lea menos, y daremos propuestas para aumentar los índices de lectura.

In [1]:
import numpy as np
import pandas as pd
import plotly.offline as py
from plotly.offline import init_notebook_mode, iplot
import plotly.graph_objs as go
import plotly.express as px
%matplotlib inline
import seaborn as sns
init_notebook_mode(connected=True)

In [2]:
#lectores=pd.read_csv("/Users/arturo/Pruebas/repoArturo/EDA copia/data/Datos_noviembre_2024_lectura.csv")
lectores = pd.read_csv("data/Datos_noviembre_2024_lectura.csv")

lectores.to_csv("lectores_preparado.csv", index=False)
pd.set_option("display.max_columns", None)
lectores.head(2)

,id,sexo,edad,edad_r,hab,prov,ccaa,hijos,edu,cs,p1,p2,p3,p4_1,p4_2,p4_3,p4_4,p4_5,p4_6,p4_7,p4_8,p4_9,p4_10,p5,p6,p7a_1,p7a_2,p7a_3,p7a_4,p7a_5,p7a_6,p7a_7,p7a_8,p7b_1,p7b_2,p7b_3,p7b_4,p7b_5,p7b_6,p7b_7,p7b_8,p7b_9,p8_1,p8_2,p8_3,p8_4,p8_5,p8_6,p8_7,p8_8,p9,p10_1,p10_2,p10_3,p10_4,p10_5,p10_6,p11_1,p11_2,p11_3,p11_4,p11_5,p11_6,p11_7,p11_8,p11_9,p11_10,p11_11,p11_12,p12_1,p12_2,p12_3,p13_1,p13_2,p13_3,p14_1,p14_2,p14_3,p14_4,p14_5,p15_1,p15_2,p15_3,p16_1,p16_2,p16_3,p16_4,p16_5,p16_6,p16_7,p16_8,p16_9,p17_1,p17_2,p17_3,p17_4,p17_5,p17_6,p17_7,p17_8,p17_9,p17_10,p17_11,p17_12,p17_13,p17_14,p17_15,p17_16,p17_17,p17_18,p18_1,p18_2,p18_3,p18_4,p18_5,p18_6,p18_7,p18_8,p18_9,p18_10,p18_11,p18_12,p18_13,p18_14,p19,p20_1,p20_2,p20_3,p20_4,p20_5,p20_6,p20_7,p20_8,p20_9,p21_1,p21_2,p21_3,p21_4,p21_5,p21_6,p21_7,p21_8,p22,p22_titulo,p22_autor,p23_1,p23_2,p23_3,p23_4,p23_5,p23_6,p23_7,p23_8,p23_9,p23_10,p24_1,p24_2,p24_3,p24_4,p24_5,p24_6,p24_7,p24_8,p24_9,p24_10,p24_11,p24_12,p24_13,p25a_1,p25a_2,p25a_3,p25a_4,p25a_5,p25a_6,p25a_7,p25a_8,p25a_9,p25a_10,p25a_11,p25a_12,p25a_13,p25a_14,p25a_15,p25a_16,p25a_17,p25b_1,p25b_2,p25b_3,p25b_4,p25b_5,p25b_6,p25b_7,p25b_8,p25b_9,p25b_10,p25b_11,p25b_12,p25b_13,p25b_14,p25b_15,p25b_16,p25b_17,p25b_18,p25b_19,p25b_20,p25b_21,p25c,p26,p26_titulo,p26_autor,p27,p27_titulo,p27_autor,p28,p29,p30,gen_r,gen_sex,hab_r,clase_social_r,situacion_laboral_r,educacion_r,ponde
0,1.0,Mujer,69.0,65+,10.001 - 20.000,Girona,Cataluña,No convivo con ningún/a hijo/a,Segundo Grado 2ª Ciclo FP Iº y IIº Bachiller ...,C,Ahorro/se ahorra un poco de dinero cada mes,PSOE (Partido Socialista Obrero Español),5,Alguna vez al mes,Todos o casi todos los días,Todos o casi todos los días,Nunca,Nunca,Nunca,Nunca,Nunca,Todos o casi todos los días,Nunca,Entre 2 y 3,Leo menos libros ahora,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Selected,Not Selected,NaN,NaN,Not Selected,Not Selected,Not Selected,Selected,Not Selected,"Si, siempre","Si, siempre","Si, siempre","Si, siempre","Si, siempre","Si, siempre","Si, siempre","Si, siempre",Menos de 10,Siempre,Nunca,Nunca,Nunca,Nunca,Nunca,No,No,No,Sí,Sí,No,No,No,No,No,No,No,No suelo leer libros que no estén escritos ori...,No suelo leer libros que no estén escritos ori...,No suelo leer libros que no estén escritos ori...,Selected,Selected,Not Selected,Not Selected,Not Selected,Selected,Not Selected,Not Selected,Más de 15 minutos y hasta 30 minutos,Más de 15 minutos y hasta 30 minutos,Más de 30 minutos y hasta 1 hora,Siempre,Nunca,Nunca,Nunca,Nunca,Nunca,Siempre,Nunca,Nunca,Poco,Nada,Nada,Nada,Poco,Nada,Nada,Nada,Nada,Nada,Nada,Mucho,Mucho,Mucho,Nada,Nada,Nada,Poco,Not Selected,Not Selected,Not Selected,Not Selected,Not Selected,Not Selected,Not Selected,Not Selected,Not Selected,Not Selected,Not Selected,Not Selected,Not Selected,Selected,Sí,Selected,Not Selected,Selected,Not Selected,Not Selected,Not Selected,Not Selected,Not Selected,Not Selected,Nada,Nada,Nada,Nada,Poco,Bastante,Nada,Nada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Sí,Sí,Sí,No,Sí,No,No,No,No,No,No,No,Sí,No,No,No,No,No,No,Sí,No,No,Sí,Sí,No,No,No,No,No,Si,No,No,No,No,No,No,No,No,No,No,Si,Si,No,Si,No,No,No,No,No,No,Depende del tema,No,NaN,NaN,No suelo regalar libros,NaN,NaN,No especifica,"Si, me gustaría leer un poco más",No pertenezco a ningún grupo o club de lectura...,Baby Boomers - Silent Generation,Mujer [Baby Boomers - Silent Generation],Más de 10.000,Media,Pensionista,"Segundo grado, segundo ciclo",1.349315
1,2.0,Mujer,47.0,45-54,< 10.000,"Rioja, La","Rioja, La","Sí, con uno/a de 0 a 8 años",Tercer Grado 1º Ciclo Equivalente a Ingeniero...,A2,Ahorro/se ahorra un poco de dinero cada mes,PP (Partido Popular),8,Una o dos veces por semana,Todos o casi todos los días,Nunca,Todos o casi todos los días,Casi nunca,Todos o casi todos los días,Nunca,Alguna vez al mes,Nunca,Todos o casi todos los días,Ninguno,Leo menos libros ahora,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Selected,Not Selected,Selected,NaN,Selected,Selected,Not Selected,Selected,Not Selected,"Si, siempre",No lo recuerdo,"Si, siempre",No lo recuerdo,"Si, siempre",No lo recuerdo,"Si, siempre","Si, a veces",Más de 50 y hasta 100,Siempre,Nunca,Nunca,Nunca,Nunca,Nunca,No,No,Sí,Sí,Sí,Sí,No,Sí,No,Sí,No,No,No suelo leer libros que no estén escritos ori...,No suelo leer libros que no estén escritos ori...,No suelo leer libros que no estén escritos ori...,Not Selected,Not Selected,Selected,Not Selected,Not Selected,Selected,Not Selected,Not Selected,15 minutos o menos,15 minutos o menos,Más de 30 minutos y hasta 1 hora,Siempre,Nunca,Nunca,Nunca,Algunas veces,Nunca,Casi nunca,Nunca,Nunca,Poco,Mucho,Poco,Mucho,Poco,Mucho,Poco,Bastante,Mucho,Poco,Mucho,Mucho,Mucho,Mucho,Poco,Poco,Poco,Poco,Not Selected,Not Selected,Not Selected,Not Selected,Not Selected,Not Selected,Not Selected,Not Selected,Not Selected,Not Selected,Selected,Not Selected,Not Selected,Not Selected,No,Not Selected,Not Selected,Selected,Not Selected,Not Selected,Not Selected,Not Selected,Not Selected,Not Selected,Nada,Mucho,Nada,Bastante,Nada,Nada,Nada,Mucho,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,No,No,No,No,Sí,No,No,No,No,No,No,Sí,No,Sí,Sí,Sí,No,No,Sí,No,No,No,No,Sí,Sí,Sí,No,No,No,No,Si,No,No,Si,Si,Si,No,Si,Si,No,No,No,No,No,No,No,Si,No,Si,Depende del tema,No,NaN,NaN,No suelo regalar libros,NaN,NaN,Arturo Pérez-Reverte,"Si, me gustaría leer mucho más",No pertenezco a ningún grupo o club de lectura...,Generacion X,Mujer [Generacion X],Menos de 10.000,Alta / Media Alta,Trabaja,"Tercer grado, primer ciclo",0.937156

PUNTO DE PARTIDA

In [3]:
#ÍNDICE DE LECTURA

### Hipótesis

Hipótesis_1 = ¡Los jóvenes no leen!

¿Con qué frecuencia haces la siguiente actividad en tu tiempo libre?
p4_1: Leer un libro

In [4]:
print(lectores.columns.tolist())

['id', 'sexo', 'edad', 'edad_r', 'hab', 'prov', 'ccaa', 'hijos', 'edu', 'cs', 'p1', 'p2', 'p3', 'p4_1', 'p4_2', 'p4_3', 'p4_4', 'p4_5', 'p4_6', 'p4_7', 'p4_8', 'p4_9', 'p4_10', 'p5', 'p6', 'p7a_1', 'p7a_2', 'p7a_3', 'p7a_4', 'p7a_5', 'p7a_6', 'p7a_7', 'p7a_8', 'p7b_1', 'p7b_2', 'p7b_3', 'p7b_4', 'p7b_5', 'p7b_6', 'p7b_7', 'p7b_8', 'p7b_9', 'p8_1', 'p8_2', 'p8_3', 'p8_4', 'p8_5', 'p8_6', 'p8_7', 'p8_8', 'p9', 'p10_1', 'p10_2', 'p10_3', 'p10_4', 'p10_5', 'p10_6', 'p11_1', 'p11_2', 'p11_3', 'p11_4', 'p11_5', 'p11_6', 'p11_7', 'p11_8', 'p11_9', 'p11_10', 'p11_11', 'p11_12', 'p12_1', 'p12_2', 'p12_3', 'p13_1', 'p13_2', 'p13_3', 'p14_1', 'p14_2', 'p14_3', 'p14_4', 'p14_5', 'p15_1', 'p15_2', 'p15_3', 'p16_1', 'p16_2', 'p16_3', 'p16_4', 'p16_5', 'p16_6', 'p16_7', 'p16_8', 'p16_9', 'p17_1', 'p17_2', 'p17_3', 'p17_4', 'p17_5', 'p17_6', 'p17_7', 'p17_8', 'p17_9', 'p17_10', 'p17_11', 'p17_12', 'p17_13', 'p17_14', 'p17_15', 'p17_16', 'p17_17', 'p17_18', 'p18_1', 'p18_2', 'p18_3', 'p18_4', 'p18_5', 'p18_6', 'p18_7', 'p18_8', 'p18_9', 'p18_10', 'p18_11', 'p18_12', 'p18_13', 'p18_14', 'p19', 'p20_1', 'p20_2', 'p20_3', 'p20_4', 'p20_5', 'p20_6', 'p20_7', 'p20_8', 'p20_9', 'p21_1', 'p21_2', 'p21_3', 'p21_4', 'p21_5', 'p21_6', 'p21_7', 'p21_8', 'p22', 'p22_titulo', 'p22_autor', 'p23_1', 'p23_2', 'p23_3', 'p23_4', 'p23_5', 'p23_6', 'p23_7', 'p23_8', 'p23_9', 'p23_10', 'p24_1', 'p24_2', 'p24_3', 'p24_4', 'p24_5', 'p24_6', 'p24_7', 'p24_8', 'p24_9', 'p24_10', 'p24_11', 'p24_12', 'p24_13', 'p25a_1', 'p25a_2', 'p25a_3', 'p25a_4', 'p25a_5', 'p25a_6', 'p25a_7', 'p25a_8', 'p25a_9', 'p25a_10', 'p25a_11', 'p25a_12', 'p25a_13', 'p25a_14', 'p25a_15', 'p25a_16', 'p25a_17', 'p25b_1', 'p25b_2', 'p25b_3', 'p25b_4', 'p25b_5', 'p25b_6', 'p25b_7', 'p25b_8', 'p25b_9', 'p25b_10', 'p25b_11', 'p25b_12', 'p25b_13', 'p25b_14', 'p25b_15', 'p25b_16', 'p25b_17', 'p25b_18', 'p25b_19', 'p25b_20', 'p25b_21', 'p25c', 'p26', 'p26_titulo', 'p26_autor', 'p27', 'p27_titulo', 'p27_autor', 'p28', 'p29', 'p30', 'gen_r', 'gen_sex', 'hab_r', 'clase_social_r', 'situacion_laboral_r', 'educacion_r', 'ponde']

AGRUPO POR SEXO y selecciono todos las respuestas a P4: 
#p4_1: ¿Con qué frecuencia lees? Leer un libro

In [5]:

#lectores = lectores[["gen_r", "sexo"] + [f"p4_{i}" for i in range(1, 11)]]
lectores = lectores[["gen_r", "sexo","p4_1"]]
print(f"Hay {lectores['p4_1'].count()} respuestas en p4_1")
lectores

Hay 2000 respuestas en p4_1

                                 gen_r    sexo                        p4_1
0     Baby Boomers - Silent Generation   Mujer           Alguna vez al mes
1                         Generacion X   Mujer  Una o dos veces por semana
2                          Millennials  Hombre     Alguna vez al trimestre
3     Baby Boomers - Silent Generation   Mujer  Una o dos veces por semana
4     Baby Boomers - Silent Generation  Hombre                  Casi nunca
...                                ...     ...                         ...
1995                      Generacion Z   Mujer                  Casi nunca
1996                       Millennials  Hombre                       Nunca
1997                      Generacion X  Hombre                       Nunca
1998                      Generacion Z  Hombre  Una o dos veces por semana
1999                      Generacion Z   Mujer                       Nunca

[2000 rows x 3 columns]

In [6]:
#SIN AGRUPAR POR SEXO
lectores_M = lectores.loc[lectores["sexo"] == "Mujer",["gen_r","p4_1"]]
print(f"Hay {lectores_M['p4_1'].count()} respuestas de mujeres a p4_1.")

Hay 1052 respuestas de mujeres a p4_1.

In [7]:
lectores_H = lectores.loc[lectores["sexo"] == "Hombre",["gen_r","p4_1"]]
print(f"Hay {lectores_H['p4_1'].count()} respuestas de hombres a p4_1.")

Hay 948 respuestas de hombres a p4_1.

TODOS LOS LECTORES

In [8]:
lectores_T=lectores.groupby("p4_1")["p4_1"].count().sort_values(ascending=False)
print(lectores_T)
print(f"Hay {lectores_T.sum()} respuestas en p4_1 de la GZ")
lectores_T_pct = (lectores_T / lectores_T.sum()*100).round(2)
print(lectores_T_pct)

p4_1
Todos o casi todos los días       502
Una o dos veces por semana        327
Alguna vez al mes                 322
Tres o cuatro veces por semana    295
Casi nunca                        242
Alguna vez al trimestre           193
Nunca                             119
Name: p4_1, dtype: int64
Hay 2000 respuestas en p4_1 de la GZ
p4_1
Todos o casi todos los días       25.10
Una o dos veces por semana        16.35
Alguna vez al mes                 16.10
Tres o cuatro veces por semana    14.75
Casi nunca                        12.10
Alguna vez al trimestre            9.65
Nunca                              5.95
Name: p4_1, dtype: float64

GENERACIÓN Z: 18-27 años.

In [9]:
lectores_GZ=lectores[lectores["gen_r"]=="Generacion Z"].groupby("p4_1")["p4_1"].count().sort_values(ascending=False)
print(lectores_GZ)
print(f"Hay {lectores_GZ.sum()} respuestas en p4_1 de la GZ")
lectores_GZ_pct = (lectores_GZ / lectores_GZ.sum()*100).round(2)
print(lectores_GZ_pct)

p4_1
Una o dos veces por semana        46
Alguna vez al mes                 43
Tres o cuatro veces por semana    41
Todos o casi todos los días       32
Alguna vez al trimestre           26
Casi nunca                        24
Nunca                             15
Name: p4_1, dtype: int64
Hay 227 respuestas en p4_1 de la GZ
p4_1
Una o dos veces por semana        20.26
Alguna vez al mes                 18.94
Tres o cuatro veces por semana    18.06
Todos o casi todos los días       14.10
Alguna vez al trimestre           11.45
Casi nunca                        10.57
Nunca                              6.61
Name: p4_1, dtype: float64

GENERACIÓN MILLENIALS: 28-43 años.

In [10]:
lectores_MIL=lectores[lectores["gen_r"]=="Millennials"].groupby("p4_1")["p4_1"].count().sort_values(ascending=False)
print(lectores_MIL)
print(f"Hay {lectores_MIL.sum()} respuestas en p4_1 de la genearación Millennials")
lectores_MIL_pct = (lectores_MIL / lectores_MIL.sum()*100).round(2)
print(lectores_MIL_pct)

p4_1
Todos o casi todos los días       107
Una o dos veces por semana         92
Alguna vez al mes                  89
Tres o cuatro veces por semana     77
Casi nunca                         60
Alguna vez al trimestre            43
Nunca                              18
Name: p4_1, dtype: int64
Hay 486 respuestas en p4_1 de la genearación Millennials
p4_1
Todos o casi todos los días       22.02
Una o dos veces por semana        18.93
Alguna vez al mes                 18.31
Tres o cuatro veces por semana    15.84
Casi nunca                        12.35
Alguna vez al trimestre            8.85
Nunca                              3.70
Name: p4_1, dtype: float64

GENERACIÓN X: 44-59 años.

In [11]:
lectores_GX=lectores[lectores["gen_r"]=="Generacion X"].groupby("p4_1")["p4_1"].count().sort_values(ascending=False)
print(lectores_GX)
print(f"Hay {lectores_GX.sum()} respuestas en p4_1 de la GX")
lectores_GX_pct = ((lectores_GX / lectores_GX.sum())*100).round(2)
print(lectores_GX_pct)

p4_1
Todos o casi todos los días       165
Una o dos veces por semana        115
Alguna vez al mes                 110
Casi nunca                         93
Tres o cuatro veces por semana     93
Alguna vez al trimestre            75
Nunca                              45
Name: p4_1, dtype: int64
Hay 696 respuestas en p4_1 de la GX
p4_1
Todos o casi todos los días       23.71
Una o dos veces por semana        16.52
Alguna vez al mes                 15.80
Casi nunca                        13.36
Tres o cuatro veces por semana    13.36
Alguna vez al trimestre           10.78
Nunca                              6.47
Name: p4_1, dtype: float64

GENERACIÓN BABY BOOM: 60+

In [12]:
lectores_BB=lectores[lectores["gen_r"]=="Baby Boomers - Silent Generation"].groupby("p4_1")["p4_1"].count().sort_values(ascending=False)
print(lectores_BB)
print(f"Hay {lectores_BB.sum()} respuestas en p4_1 de la Baby Boomers - Silent Generation")
lectores_BB_pct = (lectores_BB / lectores_BB.sum()*100).round(2)
print(lectores_BB_pct)

p4_1
Todos o casi todos los días       198
Tres o cuatro veces por semana     84
Alguna vez al mes                  80
Una o dos veces por semana         73
Casi nunca                         65
Alguna vez al trimestre            49
Nunca                              41
Name: p4_1, dtype: int64
Hay 590 respuestas en p4_1 de la Baby Boomers - Silent Generation
p4_1
Todos o casi todos los días       33.56
Tres o cuatro veces por semana    14.24
Alguna vez al mes                 13.56
Una o dos veces por semana        12.37
Casi nunca                        11.02
Alguna vez al trimestre            8.31
Nunca                              6.95
Name: p4_1, dtype: float64

GRÁFICO - H1

In [13]:
trace1={
    "x":lectores_GZ_pct.index,
    "y":lectores_GZ_pct.values,
    "name":"GZ",
    "type":"bar",
    "text": [f"" for v in lectores_GZ.values],
    "textposition":"outside",
    "marker":dict(color="teal"),
}

trace2={
    "x":lectores_MIL_pct.index,
    "y":lectores_MIL_pct.values,
    "name":"Millennials",
    "type":"bar"
    }

trace3={
    "x":lectores_GX_pct.index,
    "y":lectores_GX_pct.values,
    "name":"GX",
    "type":"bar"
}

trace4={
    "x":lectores_BB_pct.index,
    "y":lectores_BB_pct.values,
    "name":"Boomers",
    "type":"bar"
}

data=[trace1, trace2, trace3, trace4]

layout={
    "xaxis":{"title":"GENERACIONES"},
    "title": "LECTORES",
    "yaxis": {"title": "Porcentaje %"},
    
}

fig_generaciones = go.Figure(data=data, layout=layout)
fig_generaciones.update_xaxes(tickangle=30)

iplot(fig_generaciones)

Mantengo este gráfico y creo otro donde se vea qué pasa si sumo varias (AL MENOS UNA O DOS VECES POR SEMANA)
Sumar tres categorías de respuesta distintas.

In [14]:
type(lectores_T)
#print(lectores_T.head())

pandas.core.series.Series

In [15]:

# 🔹 1️⃣ Renombrar el índice antes del reset para evitar duplicados
lectores_T.index.name = "respuesta"

# 🔹 2️⃣ Convertir la Serie a DataFrame
df = lectores_T.reset_index()

# 🔹 3️⃣ Renombrar columnas (si es necesario)
df.columns = ["respuesta", "lectores"]

# 🔹 4️⃣ Filas que quieres agrupar
a_agrupar = [
    "Una o dos veces por semana",
    "Tres o cuatro veces por semana",
    "Todos o casi todos los días"
]

# 🔹 5️⃣ Crear la nueva fila resumen
fila_resumen = pd.DataFrame([{
    "respuesta": "Al menos dos veces por semana",
    "lectores": df.loc[df["respuesta"].isin(a_agrupar), "lectores"].sum()
}])

# 🔹 6️⃣ Eliminar las filas agrupadas
df_filtrado = df[~df["respuesta"].isin(a_agrupar)]

# 🔹 7️⃣ Añadir la nueva fila
df_final = pd.concat([df_filtrado, fila_resumen], ignore_index=True)

# 🔹 8️⃣ (Opcional) Ordenar por número de lectores
df_final = df_final.sort_values("lectores", ascending=False).reset_index(drop=True)

print(df_final)

                       respuesta  lectores
0  Al menos dos veces por semana      1124
1              Alguna vez al mes       322
2                     Casi nunca       242
3        Alguna vez al trimestre       193
4                          Nunca       119

GENERACIÓN Z _ AGRUPADA: 18-27 años.

In [16]:
#Lectores_GZ es una Serie. La convertimos en DataFrame.
df_gz = lectores_GZ.rename_axis("respuesta").reset_index(name="lectores")

#Filas que vamos a agrupar
a_agrupar = [
    "Una o dos veces por semana",
    "Tres o cuatro veces por semana",
    "Todos o casi todos los días"
]

#Creamos la nueva fila agrupada con la suma
fila_resumen = pd.DataFrame([{
    "respuesta": "Al menos dos veces por semana",
    "lectores": df_gz.loc[df["respuesta"].isin(a_agrupar), "lectores"].sum()
}])

#Eliminamos las filas originales que acabas de agrupar
df_filtrado_gz = df_gz[~df_gz["respuesta"].isin(a_agrupar)]

#Añadimos la nueva fila de resumen al final
df_final_gz = pd.concat([df_filtrado_gz, fila_resumen], ignore_index=True)

#Reordenamos por número de lectores, de mayor a menor
df_final_gz = df_final_gz.sort_values("lectores", ascending=False).reset_index(drop=True)

#print(df_final_gz)

lectores_GZ_a_pct = (df_final_gz["lectores"] / df_final_gz["lectores"].sum() * 100).round(2)

df_final_gz["porcentaje"]=lectores_GZ_a_pct

print(df_final_gz)

#print(lectores_GZ_pct)

                       respuesta  lectores  porcentaje
0  Al menos dos veces por semana       121       52.84
1              Alguna vez al mes        43       18.78
2        Alguna vez al trimestre        26       11.35
3                     Casi nunca        24       10.48
4                          Nunca        15        6.55

GENERACIÓN MILLENNIAL AGRUPADA: 28-43 años.

In [17]:
#Lectores_ Millennial es una Serie. La convertimos en DataFrame.
df_mil = lectores_MIL.rename_axis("respuesta").reset_index(name="lectores")

#Filas que vamos a agrupar
a_agrupar = [
    "Una o dos veces por semana",
    "Tres o cuatro veces por semana",
    "Todos o casi todos los días"
]

#Creamos la nueva fila agrupada con la suma
fila_resumen = pd.DataFrame([{
    "respuesta": "Al menos dos veces por semana",
    "lectores": df_mil.loc[df_mil["respuesta"].isin(a_agrupar), "lectores"].sum()
}])

#Eliminamos las filas originales que acabas de agrupar
df_filtrado_mil = df_mil[~df_mil["respuesta"].isin(a_agrupar)]

#Añadimos la nueva fila de resumen al final
df_final_mil = pd.concat([df_filtrado_mil, fila_resumen], ignore_index=True)

#Reordenamos por número de lectores, de mayor a menor
df_final_mil = df_final_mil.sort_values("lectores", ascending=False).reset_index(drop=True)

df_final_mil


lectores_mil_a_pct = (df_final_mil["lectores"] / df_final_mil["lectores"].sum() * 100).round(2)

df_final_mil["porcentaje"]=lectores_mil_a_pct

print(df_final_mil)

                       respuesta  lectores  porcentaje
0  Al menos dos veces por semana       276       56.79
1              Alguna vez al mes        89       18.31
2                     Casi nunca        60       12.35
3        Alguna vez al trimestre        43        8.85
4                          Nunca        18        3.70

GENERACIÓN X AGRUPADA: 44-59 años.

In [18]:
#Lectores_ X es una Serie. La convertimos en DataFrame.
df_gx = lectores_GX.rename_axis("respuesta").reset_index(name="lectores")

#Filas que vamos a agrupar
a_agrupar = [
    "Una o dos veces por semana",
    "Tres o cuatro veces por semana",
    "Todos o casi todos los días"
]

#Creamos la nueva fila agrupada con la suma
fila_resumen = pd.DataFrame([{
    "respuesta": "Al menos dos veces por semana",
    "lectores": df_gx.loc[df_gx["respuesta"].isin(a_agrupar), "lectores"].sum()
}])

#Eliminamos las filas originales que acabas de agrupar
df_filtrado_gx = df_gx[~df_gx["respuesta"].isin(a_agrupar)]

#Añadimos la nueva fila de resumen al final
df_final_gx = pd.concat([df_filtrado_gx, fila_resumen], ignore_index=True)

#Reordenamos por número de lectores, de mayor a menor
df_final_gx = df_final_gx.sort_values("lectores", ascending=False).reset_index(drop=True)

df_final_gx

lectores_gx_a_pct = (df_final_gx["lectores"] / df_final_gx["lectores"].sum() * 100).round(2)

df_final_gx["porcentaje"]=lectores_gx_a_pct

print(df_final_gx)

                       respuesta  lectores  porcentaje
0  Al menos dos veces por semana       373       53.59
1              Alguna vez al mes       110       15.80
2                     Casi nunca        93       13.36
3        Alguna vez al trimestre        75       10.78
4                          Nunca        45        6.47

GENERACIÓN BABY BOOM AGRUPADA: 60+ años.

In [19]:
#Lectores_ X es una Serie. La convertimos en DataFrame.
df_bb = lectores_BB.rename_axis("respuesta").reset_index(name="lectores")

#Filas que vamos a agrupar
a_agrupar = [
    "Una o dos veces por semana",
    "Tres o cuatro veces por semana",
    "Todos o casi todos los días"
]

#Creamos la nueva fila agrupada con la suma
fila_resumen = pd.DataFrame([{
    "respuesta": "Al menos dos veces por semana",
    "lectores": df_bb.loc[df_bb["respuesta"].isin(a_agrupar), "lectores"].sum()
}])

#Eliminamos las filas originales que acabas de agrupar
df_filtrado_bb = df_bb[~df_bb["respuesta"].isin(a_agrupar)]

#Añadimos la nueva fila de resumen al final
df_final_bb = pd.concat([df_filtrado_bb, fila_resumen], ignore_index=True)

#Reordenamos por número de lectores, de mayor a menor
df_final_bb = df_final_bb.sort_values("lectores", ascending=False).reset_index(drop=True)

df_final_bb

lectores_bb_a_pct = (df_final_bb["lectores"] / df_final_bb["lectores"].sum() * 100).round(2)

df_final_bb["porcentaje"]=lectores_bb_a_pct

print(df_final_bb)

                       respuesta  lectores  porcentaje
0  Al menos dos veces por semana       355       60.17
1              Alguna vez al mes        80       13.56
2                     Casi nunca        65       11.02
3        Alguna vez al trimestre        49        8.31
4                          Nunca        41        6.95

GRÁFICO H1 - AGRUPADA

In [20]:
trace1={
    "x": df_final_gz["respuesta"],
    "y": df_final_gz["porcentaje"],
    "name":"GZ",
    "type":"bar",
    #"text": [f"" for v in df_final_gz.values],
    "text": [f"texto" for v in lectores_gx_a_pct.values],
    
    "textposition":"outside",
    "marker":dict(color="teal"),
}

trace2={
    "x": df_final_mil["respuesta"],
    "y": df_final_mil["porcentaje"],
    "name":"Millennials",
    "type":"bar"
    }

trace3={
    "x": df_final_gx["respuesta"],
    "y": df_final_gx["porcentaje"],
    "name":"GX",
    "type":"bar"
}

trace4={
    "x": df_final_bb["respuesta"],
    "y": df_final_bb["porcentaje"],
    "name":"Boomers",
    "type":"bar"
}

data=[trace1, trace2, trace3, trace4]

layout={
    "xaxis":{"title":"GENERACIONES"},
    "title": "LECTORES",
    "yaxis": {"title": "Porcentaje %"},
    
}

fig_generaciones_agrupadas=go.Figure(data=data, layout=layout)
fig_generaciones_agrupadas.update_xaxes(tickangle=30)
iplot(fig_generaciones_agrupadas)

Si solo nos quedamos con: Al menos dos veces por semana

In [21]:
filtro = "Al menos dos veces por semana"
df_filtrado_1 = df_final_gz[df_final_gz["respuesta"] == filtro]
df_filtrado_2 = df_final_mil[df_final_mil["respuesta"] == filtro]
df_filtrado_3 = df_final_gx[df_final_gx["respuesta"] == filtro]
df_filtrado_4 = df_final_bb[df_final_bb["respuesta"] == filtro]

print(df_filtrado_4)

trace1={
    "x": df_filtrado_1["respuesta"],
    "y": df_final_gz["porcentaje"],
    "name":"GZ",
    "type":"bar",
    "text": [f"texto" for v in lectores_gx_a_pct.values],
    "textposition":"outside",
    "marker":dict(color="teal"),
}
trace2={
    "x": df_filtrado_2["respuesta"],
    "y": df_final_mil["porcentaje"],
    "name":"Millennials",
    "type":"bar"
    }
trace3={
    "x": df_filtrado_3["respuesta"],
    "y": df_final_gx["porcentaje"],
    "name":"GX",
    "type":"bar"
}
trace4={
    "x": df_filtrado_4["respuesta"],
    "y": df_final_bb["porcentaje"],
    "name":"Boomers",
    "type":"bar"
}

data=[trace1, trace2, trace3, trace4]

layout={
    "xaxis":{"title":"GENERACIONES"},
    "title": "LECTORES",
    "yaxis": {"title": "Porcentaje %"},
    
}

fig=go.Figure(data=data, layout=layout)
fig.update_xaxes(tickangle=0)

iplot(fig)

                       respuesta  lectores  porcentaje
0  Al menos dos veces por semana       355       60.17

PUNTO DE PARTIDA
EL 15% de la población no ha leído ningún libro en los últimos 12 meses.
y es el 29,5% si sumamos a los que han leído 1.
Casi un tercio de la población no ha leído más de 1 libro en el último año.
El sector... podría estar mejor.

In [22]:
lectores = pd.read_csv("data/Datos_noviembre_2024_lectura.csv")

#lectores.head(2)
lectores[["p5"]].count()

p5    2000
dtype: int64

In [23]:
libros_leidos=lectores.groupby("p5")[["id"]].count()
libros_leidos.index.name="respuesta"
df=libros_leidos.reset_index()
df.columns=["respuesta","lectores"]
df.sort_values("lectores", ascending=False)

       respuesta  lectores
2    Entre 2 y 3       559
3    Entre 4 y 6       435
7            Uno       288
6        Ninguno       286
4   Entre 7 y 10       194
0  Entre 11 y 15       100
5      Más de 20        92
1  Entre 16 y 20        46

In [24]:
colores_flat9 = [
    "#2ecc71",  # Verde esmeralda
    "#e67e22",  # Naranja intenso
    "#34495e",  # Azul gris oscuro
    "#16a085"   # Verde azulado oscuro
    "#1abc9c",  # Turquesa
    "#3498db",  # Azul claro
    "#f39c12",  # Naranja dorado
    "#e74c3c",  # Rojo
    "#9b59b6",  # Violeta
]

colores=colores_flat9

fig_pie1 = go.Figure(
    go.Pie(
        labels=df.respuesta,
        values=df.lectores,
        textinfo="label+percent",
        hole=0.3,
        #marker=dict(colors=colores)
        marker=dict(colors=colores)

    )
)


fig_pie1.update_layout(
    title="Distribución porcentual de lectores",
    template="plotly_white"
)
fig_pie1.show()

In [25]:
a_agrupar=["Ninguno","Uno","Entre 2 y 3"]

file_resumen=pd.DataFrame([{
    "respuesta":"3 o menos",
    "lectores": df.loc[df["respuesta"].isin(a_agrupar),"lectores"].sum()
}])
df_filtrado = df[~df["respuesta"].isin(a_agrupar)]
df_final = pd.concat([df_filtrado, file_resumen], ignore_index=True)
df_final = df_final.sort_values("lectores", ascending=False).reset_index(drop=True)
print(df_final)

       respuesta  lectores
0      3 o menos      1133
1    Entre 4 y 6       435
2   Entre 7 y 10       194
3  Entre 11 y 15       100
4      Más de 20        92
5  Entre 16 y 20        46

In [26]:
colores_flat9_a = [
    "#e74c3c",  # Rojo
    "#1abc9c",  # Turquesa
    "#3498db",  # Azul claro
    "#f39c12",  # Naranja dorado
    "#9b59b6",  # Violeta
    "#2ecc71",  # Verde esmeralda
    "#e67e22",  # Naranja intenso
    "#34495e",  # Azul gris oscuro
    "#16a085"   # Verde azulado oscuro
]

colores=colores_flat9_a

fig_pie2 = go.Figure(
    go.Pie(
        labels=df_final["respuesta"],
        values=df_final["lectores"],
        textinfo="label+percent",
        hole=0.3,
        marker=dict(colors=colores_flat9)
    )
)
fig_pie2.update_layout(
    title="Distribución porcentual de lectores",
    template="plotly_white"
)

Profundizando un poco más:

Si preguntamos: ¿Cuántos libros has leído en los últimos 12 meses? P5

El porcentaje de la G.Z que ha leído más de 3 libros es el 44,5%, por encima del  62,7% (37,3%, sí) de la G.X (44-59 años) que confiesa no haber leído más de 3 libros en el último año.

Coclusión: "La edad no es factor determinante"

In [27]:

lectores = pd.read_csv("data/Datos_noviembre_2024_lectura.csv")

pd.set_option("display.max_columns", None)
lectores = lectores[["gen_r", "sexo","p5"]]

print(lectores.groupby("gen_r")["p5"].value_counts())

#lectores = lectores.rename(columns={"p5": "Libros leídos en un año"})

lectores.head(10)

gen_r                             p5
Baby Boomers - Silent Generation  Entre 2 y 3      146
                                  Entre 4 y 6      127
                                  Ninguno           91
                                  Uno               74
                                  Entre 7 y 10      59
                                  Entre 11 y 15     38
                                  Más de 20         38
                                  Entre 16 y 20     17
Generacion X                      Entre 2 y 3      207
                                  Entre 4 y 6      127
                                  Ninguno          114
                                  Uno              112
                                  Entre 7 y 10      62
                                  Entre 11 y 15     28
                                  Más de 20         28
                                  Entre 16 y 20     18
Generacion Z                      Entre 2 y 3       71
                                  Entre 4 y 6       59
                                  Uno               27
                                  Ninguno           26
                                  Entre 7 y 10      19
                                  Entre 11 y 15     16
                                  Más de 20          7
                                  Entre 16 y 20      2
Millennials                       Entre 2 y 3      135
                                  Entre 4 y 6      122
                                  Uno               75
                                  Ninguno           55
                                  Entre 7 y 10      54
                                  Entre 11 y 15     18
                                  Más de 20         18
                                  Entre 16 y 20      9
Name: count, dtype: int64

                              gen_r    sexo             p5
0  Baby Boomers - Silent Generation   Mujer    Entre 2 y 3
1                      Generacion X   Mujer        Ninguno
2                       Millennials  Hombre    Entre 2 y 3
3  Baby Boomers - Silent Generation   Mujer    Entre 2 y 3
4  Baby Boomers - Silent Generation  Hombre        Ninguno
5  Baby Boomers - Silent Generation   Mujer    Entre 4 y 6
6  Baby Boomers - Silent Generation   Mujer    Entre 4 y 6
7  Baby Boomers - Silent Generation  Hombre    Entre 4 y 6
8                      Generacion X  Hombre  Entre 11 y 15
9  Baby Boomers - Silent Generation   Mujer  Entre 11 y 15

In [28]:
generacion="TODAS"
lectores=lectores.groupby("p5")["p5"].count().sort_values(ascending=False)
print(lectores)
print(f"Hay {lectores.sum()} respuestas en p5")
lectores_pct = (lectores / lectores.sum()*100).round(2)
print(lectores_pct)

p5
Entre 2 y 3      559
Entre 4 y 6      435
Uno              288
Ninguno          286
Entre 7 y 10     194
Entre 11 y 15    100
Más de 20         92
Entre 16 y 20     46
Name: p5, dtype: int64
Hay 2000 respuestas en p5
p5
Entre 2 y 3      27.95
Entre 4 y 6      21.75
Uno              14.40
Ninguno          14.30
Entre 7 y 10      9.70
Entre 11 y 15     5.00
Más de 20         4.60
Entre 16 y 20     2.30
Name: p5, dtype: float64

Hipótesis 2:

Y si la edad no es un factor clave… ¿qué explica que leamos menos?
Creemos que son los móviles los culpables.  (Pág. 12)

A la pregunta: ¿Por qué ahora lees menos libros que hace 10 años?
EL 47,6% (casi la mitad) confiesa que ahora consume más series y películas.

Conclusión: “El lector se ha ido al cine”… o mejor dicho, a Netflix. Las plataformas con su oferta de series y películas son el mayor (gran) ladrón de lectores, seguido de lejos (un 34%) por la falta de tiempo libre y,, en tercer lugar, por el móvil; entendido como herramienta para el consumo de tiempo dedicado a las RRSS: Instagram, YouTube, TikTok (31,3%).

In [29]:
lectores.head(20)

p5
Entre 2 y 3      559
Entre 4 y 6      435
Uno              288
Ninguno          286
Entre 7 y 10     194
Entre 11 y 15    100
Más de 20         92
Entre 16 y 20     46
Name: p5, dtype: int64

p7b_1: Dispongo de menos tiempo libre para ocio.

p7b_2:Me resulta más difícil encontrar libros que me gusten

p7b_3:Paso más tiempo jugando juegos con el móvil

p7b_4:Paso más tiempo jugando videojuegos (en el ordenador, con consolas, etc)

p7b_5:Dedico más tiempo a las redes sociales (Instagram, YouTube, TikTok, etc.)

p7b_6:Veo más series y películas

p7b_7:Ha empeorado mi salud (visión, etc.)

p7b_8:Por mi momento vital, ahora disfruto menos de la lectura

p7b_9:Otros motivos

In [30]:
lectores = pd.read_csv("data/Datos_noviembre_2024_lectura.csv")

pd.set_option("display.max_columns", None)

lectores = lectores[[f"p7b_{i}" for i in range(1, 10)]]

lectores[[f"p7b_{i}" for i in range(1, 10)]].value_counts()

#lectores = lectores.rename(columns={"p5": "Libros leídos en un año"})

porcentajes_selected = (lectores[[f"p7b_{i}" for i in range(1, 10)]] == "Selected").mean() * 100

#print(porcentajes_selected)


for col in [f"p7b_{i}" for i in range(1, 10)]:
    conteos = lectores[col].value_counts()
    total = conteos.sum()
    selected = conteos.get("Selected", 0)
    porcentaje = (selected / total) * 100 if total > 0 else 0
    print(f"{col}: {selected}/{total} ({porcentaje:.1f}%) Selected")

p7b_1: 314/877 (35.8%) Selected
p7b_2: 139/877 (15.8%) Selected
p7b_3: 145/672 (21.6%) Selected
p7b_4: 67/471 (14.2%) Selected
p7b_5: 279/877 (31.8%) Selected
p7b_6: 414/877 (47.2%) Selected
p7b_7: 161/877 (18.4%) Selected
p7b_8: 148/877 (16.9%) Selected
p7b_9: 62/877 (7.1%) Selected

In [31]:
# 1) Construimos una tabla con tus datos del bucle
cols = [f"p7b_{i}" for i in range(1, 10)]
resumen = []

for col in cols:
    conteos = lectores[col].value_counts()
    total = conteos.sum()
    selected = conteos.get("Selected", 0)
    porcentaje = (selected / total) * 100 if total > 0 else 0
    resumen.append({"pregunta": col, "Selected": selected, "Total": total, "% Selected": porcentaje})

df_pct = pd.DataFrame(resumen).sort_values("% Selected", ascending=True)  # orden para ranking horizontal


# Nombres personalizados para las etiquetas del eje Y
map_y = {
    "p7b_1":"Dispongo de menos tiempo libre para ocio", "p7b_2":"Me resulta más difícil encontrar libros que me gusten", "p7b_3":"Paso más tiempo jugando juegos con el móvil",
    "p7b_4":"Paso más tiempo jugando videojuegos (en el ordenador, con consolas, etc)",  "p7b_5":"Dedico más tiempo a las redes sociales (Instagram, YouTube, TikTok, etc.)","p7b_6":"Veo más series y películas",
    "p7b_7":"Ha empeorado mi salud (visión, etc.)","p7b_8":"Por mi momento vital, ahora disfruto menos de la lectura", "p7b_9":"Otros motivos"
}

# df_pct ya está ORDENADO por % Selected
df_pct["etiqueta_y"] = df_pct["pregunta"].map(map_y).fillna(df_pct["pregunta"])

# 2) Gráfico con trace (go.Bar)
trace = go.Bar(
    x=df_pct["% Selected"].values,           # porcentaje en X
    y=df_pct["etiqueta_y"].values,   # ← usa la etiqueta mapeada TRAS ordenar
    orientation="h",
    text=[f"{v:.1f}%" for v in df_pct["% Selected"].values],
    textposition="outside",
    marker=dict(color="teal"),
    name="% Selected"
)


layout = go.Layout(
    title="Ranking de % de 'Selected' por ítem (p7b_1 … p7b_9)",
    xaxis=dict(title="% Selected", range=[0, 100]),  # ejes en 0–100%
    yaxis=dict(title="Ítem"),
    template="plotly_white",
    height=500
)

#cambiar los nombre de las etiquetas
fig = go.Figure(data=[trace], layout=layout)

fig.show()


#fig = go.Figure(data=[trace], layout=layout)
#fig.show()

EL 47,6% (casi la mitad) confiesa que ahora consume más series y películas.

Conclusión: “El lector se ha ido al cine”… o mejor dicho, a Netflix. Las plataformas con su oferta de series y películas son el mayor (gran) ladrón de lectores, seguido de lejos (un 34%) por la falta de tiempo libre y,, en tercer lugar, por el móvil; entendido como herramienta para el consumo de tiempo dedicado a las RRSS: Instagram, YouTube, TikTok (31,3%).

¿Qué podemos hacer? ¿Show me the money?
Sugerencia de negocio:
Si el lector se ha ido a Netflix, vayamos a Netflix a por el... hagamos libros basados en series. (Igual que las series y el cine hace películas basadas en libros).

## OBTENCIÓN DE LOS DATOS

### DATASETS Y FUENTES DE DATOS

In [32]:
import pandas as pd
import matplotlib.pyplot as plt


#1. Leer el archivo .sav
df_sav = pd.read_spss("data/Datos_noviembre_2024_lectura.sav")

#2. Guardarlo como CSV
df_sav.to_csv("data/Datos_noviembre_2024_lectura.csv", index=False)


#3. Leer el CSV y guardar la fuente
df = pd.read_csv("data/Datos_noviembre_2024_lectura.csv")
fuente_1 = "https://ladespensa.40db.es/"

fuente_descripcion="Entrevistas/muestra (2000). Radiografía de la lectura en el siglo XXI - noviembre 2024 - 40db - España"